# Default values for the raid_fs role
#
# The actual RAID array and filesystem configuration should be defined in the
# inventory (e.g. ``group_vars/all.yml``).  Interactive helper scripts expect to
# modify variables in that location.
xiraid_license_path: "/tmp/license"

# Whether to pass `--force_metadata` when creating arrays
# Set to `false` if metadata should not be overwritten
xiraid_force_metadata: true

# RAID array and filesystem definitions should be supplied via inventory
# variables (e.g. in ``group_vars/all.yml``).  Keeping them empty here avoids
# duplicating configuration.
xiraid_arrays: []
xfs_filesystems: []
