doca_distro_series: "ubuntu{{ ansible_distribution_version }}"
doca_version: "latest"         # NVIDIA repo alias to the most recent DOCA-Host release
doca_repo_base: "https://linux.mellanox.com/public/repo/doca"
doca_repo_component: "{{ doca_version }}/{{ doca_distro_series }}/x86_64"

doca_pkgs:
  - doca-all           # DOCA-Host "Everything" profile (drivers, userspace, tools)
  - mlnx-fw-updater    # NIC firmware updater
  - mlnx-nfsrdma-dkms  # Kernel module required for NFS over RDMA

doca_ofed_auto_reboot: false

# Netplan template containing desired InfiniBand names
ib_netplan_template: "/opt/provision/collection/roles/net_controllers/templates/netplan.yaml.j2"
# Location of generated udev rules for InfiniBand
ib_udev_rules_file: "/etc/udev/rules.d/70-ib-names.rules"
