# xiRAID version to install (use 4.x.y). The repo package is auto-derived.
xiraid_version: "4.2.0"

# Repo package filename for current kernel (override if you mirror files)
# Example: xiraid-repo_1.2.0-1462.kver.6.8_amd64.deb
xiraid_repo_filename: "xiraid-repo_1.2.0-1462.kver.{{ ansible_kernel }}_amd64.deb"

# Base URL to Xinnor repository (multi-pack works for 20.04/22.04/24.04)
xiraid_repo_base_url: "https://pkg.xinnor.io/repository/Repository/xiraid/ubuntu/multi-pack"

xiraid_repo_url: "{{ xiraid_repo_base_url }}/{{ xiraid_repo_filename }}"

# List of xiRAID packages; adjust if version scheme changes.
xiraid_packages:
  - xiraid-core
  - xicli

# Whether to reboot automatically after install (usually not required)
xiraid_auto_reboot: false
