---
# Handlers for roce_lossless role

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart openibd
  ansible.builtin.service:
    name: openibd
    state: restarted
