- name: Ensure build dependencies are present
  apt:
    name:
      - dkms
      - build-essential
      - linux-headers-{{ ansible_kernel }}
      - libelf-dev
    state: present
  tags: [ofed, deps]

- name: Download DOCA-OFED repo package
  get_url:
    url: "{{ doca_ofed_dl_url }}"
    dest: "/tmp/{{ doca_ofed_repo_deb }}"
    mode: '0644'
    force: no
  tags: [ofed, download]

- name: Add DOCA-OFED APT repository (.deb)
  apt:
    deb: "/tmp/{{ doca_ofed_repo_deb }}"
    state: present
  register: repo_added
  tags: [ofed, repo]

- name: Update APT cache (if repo added)
  apt:
    update_cache: yes
  when: repo_added is changed
  tags: [ofed, repo]

- name: Install DOCA-OFED components (DKMS will build modules)
  apt:
    name: "{{ doca_ofed_components }}"
    state: present
  register: ofed_pkgs
  tags: [ofed, install]

- name: Reboot if kernel modules built and reboot requested
  reboot:
    msg: "Reboot after DOCA-OFED install (role doca_ofed)"
    reboot_timeout: 1200
  when: ofed_pkgs is changed and doca_ofed_auto_reboot | bool
  tags: [ofed, reboot]
