# -------------------------------------------------------------
# handlers/main.yml
# -------------------------------------------------------------
---
- name: reload sysctl
  ansible.builtin.command: sysctl --system

